### ISSUE TITLE
Node.js version

### ISSUE THREAD

**Issue by guelz** [SOELexicon/burst-pool#2]
Lex,  please mention node.js version in the README! (last LTS, 4.7.1 seams to be good)

also 8.8.8.8 is a bad example since its googles DNS!-)

**Comment by SOELexicon** [comment]
https://nodejs.org/download/release/v5.12.0/ is the latest you can use from what ive been told from other users. its in the forum thread. ill add this to the readme along with a link to the forum thread

i personally used 4.7.1,
V6 upwards breaks it as theres a lot of change's. such as ones to hasownproperty on query's only and the way callbacks are handled.

also 8.8.8.8 is only an example and shouldn't really make a difference as all that takes is an IP address anyway i could specify 127.0.0.1 instead or local host but as its a redirect feature i thought i should use an address that isnt mine or on a local network. most people wont even know its googles dns server.

**Comment by guelz** [comment]
pleas put it in the README. its hidden in the forums....
see https://github.com/guelz/burst-pool/issues/5

**Comment by SOELexicon** [comment]
its allready added guelz. i added it in before i posted the above

**Comment by SOELexicon** [comment]
also i commented on that thread and added my input
